--- 
version: 2.1
orbs:
    #force a run
    snyk: snyk/snyk@1.4.0
jobs: 
  build: 
    docker: 
      - 
        image: "circleci/openjdk:8-jdk-browsers"
    steps: 
      - checkout
      - snyk/scan 
      -         
        restore_cache: 
          key: "spring-rest-helloworld-{{ checksum \"pom.xml\" }}"
      - 
        run: "mvn dependency:go-offline"
      - 
        save_cache: 
          key: "circleci-demo-java-spring-{{ checksum \"pom.xml\" }}"
          paths: 
            - ~/.m2
      - 
        run: "mvn package"
      - 
        store_test_results: 
          path: target/surefire-reports
      - 
        store_artifacts: 
          path: target/spring-rest-helloworld-0.0.1-SNAPSHOT.war
      - 
        run: 
          command: "if mvn -q -Dexec.executable=\"echo\" -Dexec.args='${project.version}' --non-recursive exec:exec | grep -q \"SNAPSHOT\"; then mvn versions:set -DremoveSnapshot; fi;\n\
              echo $(mvn -q -Dexec.executable=\"echo\" -Dexec.args='${project.version}' --non-recursive exec:exec)-$(echo $CIRCLE_SHA1 | cut -c -7)-$CIRCLE_BUILD_NUM > tempvers.txt\n\
              mvn versions:set -DnewVersion=$(cat tempvers.txt) \n"
          name: "remove snapshot version"
    working_directory: ~/spring-rest-helloworld
